CREATE DATABASE CENGDB;

USE CENGDB;

CREATE TABLE USER(
	ID INT NOT NULL AUTO_INCREMENT,
    UEMAIL VARCHAR(30) NOT NULL unique,
    UPASSWORD CHAR(60) NOT NULL,
    UTYPE VARCHAR(30) NOT NULL,
    UNAMESURNAME VARCHAR(30) NOT NULL,
    UTITLE VARCHAR(30) NOT NULL,
	PRIMARY KEY (ID));
    
INSERT INTO USER(UEMAIL, UPASSWORD,UTYPE, UNAMESURNAME, UTITLE)
VALUES ('app@ceng.com', '$2a$05$77azOIF/ZCDBVhIHPLZhseNg/H6nsMjcAIZ1NgAoV/YkN0GDo4N.e', 'Admin', 'App CENG', 'App');

create table EMAIL_MEMBER(
	EMAIL varchar(30),
    NAMESURNAME varchar(30) not null,
    GRADE int not null,
    primary key(EMAIL));
    
create table EMAIL_MEMBER_GROUP(
    MEMBER_EMAIL varchar(30),
    GROUP_NAME varchar(30),
    primary key(MEMBER_EMAIL, GROUP_NAME));
    
create table EMAIL_GROUP(
    NAME varchar(30),
    primary key(NAME));