CREATE DATABASE CENGDB;

USE CENGDB;

CREATE TABLE USER(
	ID INT NOT NULL AUTO_INCREMENT,
    UEMAIL VARCHAR(30) NOT NULL unique,
    UPASSWORD CHAR(60) NOT NULL,
    UTYPE VARCHAR(30) NOT NULL,
    UNAMESURNAME VARCHAR(30) NOT NULL,
    UTITLE VARCHAR(30) NOT NULL,
	PRIMARY KEY (ID));
    
INSERT INTO USER(UEMAIL, UPASSWORD,UTYPE, UNAMESURNAME, UTITLE)
VALUES ('app@ceng.com', '$2a$05$77azOIF/ZCDBVhIHPLZhseNg/H6nsMjcAIZ1NgAoV/YkN0GDo4N.e', 'Admin', 'App CENG', 'App');
