CREATE DATABASE CENGDB;

USE CENGDB;

CREATE TABLE USER(
	ID INT NOT NULL AUTO_INCREMENT,
    UEMAIL VARCHAR(30) NOT NULL unique,
    UPASSWORD CHAR(60) NOT NULL,
    UTYPE VARCHAR(30) NOT NULL,
    UNAMESURNAME VARCHAR(30) NOT NULL,
    UTITLE VARCHAR(30) NOT NULL,
	PRIMARY KEY (ID));
    
